[package]
name = "mdm-storage"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
color-eyre.workspace = true
diesel.workspace = true
diesel_migrations.workspace = true
chrono.workspace = true
tracing.workspace = true
uuid.workspace = true
mdm-core.workspace = true
