[package]
name = "mdm-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
color-eyre.workspace = true
serde.workspace = true
plist.workspace = true
chrono.workspace = true
uuid.workspace = true
